language: - java


jdk: - oraclejdk8

before script: - chmod +x gradlew

script : - ./gradlew check
- ./gradlew jacocoTestReport
- ./gradlew assemble



after_success: - bash <(curl -s https://codecov.io/bash)
