language: - java


jdk: - oraclejdk8

before script: - chmod +x gradlew

script :
- ./gradlew assemble
  - ./gradlew check --stacktrace --info
  - ./gradlew jacocoTestReport




after_success: - bash <(curl -s https://codecov.io/bash)
